version: 0.1.{build}
image: Visual Studio 2019

build:
  verbosity: minimal

init:
  - git config --global core.autocrlf input

build_script:
  - ps: ./install.ps1
  - ps: dotnet publish src/WebFsc.Client/ -o $PWD/publish/ -c Release
  - ps: cp src/WebFsc.Client/blazor.webassembly.js publish/wwwroot/_framework/

for:
  - branches:
      only:
        - master
    on_success:
      - ps: .\tools\gh-pages.ps1 -env appveyor

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL
