version: 0.1.{build}
image: Visual Studio 2017

build:
  verbosity: minimal

init:
  - git config --global core.autocrlf input
  - ps: .\install.ps1

build_script:
  - ps: dotnet publish src/WebFsc.Client/ -o $PWD/publish/ -c Release

for:
  - branches:
      only:
        - master
    on_success:
      - ps: .\tools\gh-pages.ps1 -env appveyor

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL
